<?php

/**
 * SAMA SEPERTI KODE PERCABANGAN IF ELSE DENGAN BAHASA PEMOGRAMAN LAINNYA
 * TETAPI DI DALAM PHP BISA MENGGUNAKAN :
 * CONTOH SEPERTI BERIKUT.
 */

$nilaiAbsen = 60;
$nilaiTugag = 80;

// UNTUK MENGGANTI KURANG KURAWAL DI BAGIAN AKHIR IF ATAU ELSE IF MENGGUNAKAN :
// DI AKHIR HARUS DI AKHIRI DENGAN ENDIF;
// JIKA TIDAK AKAN TERJADI ERROR
if ($nilaiAbsen >= 75 or $nilaiTugag >= 75) :
    echo "Selamat Anda Lulus";
else:
        echo "Anda Gagal";
endif;