<?php
/**
 * DISINI KITA AKAN MEMBUAT SEBUAH OPERATOR TENNARRY,SAMA SEPERTI PENGONDISIAN IF ELSE
 * DAN SAMA JUGA SAMA SEPERTI BAHASA PEMOGRAMAN LAINNYA YA,TETAPI DISINI KITA HARUS MENGGUNAKAN ==
 * UNTUK MELIHAT HASILNYA TERLEBIH DAHULU BARU MENENTUKAN NILAINYA.
 * SEPERTI CONTOH KODE BERIKUT :
 */

$name = "Royhans";

// seperti contoh kode berikut:
$nama = $name == "Royhan" ? "itu adalah namaku" : "itu bukan namaku";
echo $nama;